# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29468219f83c6e4d422759568e37c0f1bb4f329ea55dc7be4934f35e547692ae24fccf600664b30b1344a7d6bc462c70c32c53756cb3f702411c9da04f6a76c9

test:
  secret_key_base: 679b95894a043e678a4fb22eec8c820019df0fed1fcaeda180771102facd0f31db4f6eb4e54edc7bcefb1aa0aa9bf2d52123d61db6ed6d2531afae39ab7ddedc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
